### ISSUE TITLE
Android build failing with Ionic

### ISSUE THREAD

**Issue by YogliB** [Anyline/anyline-ocr-cordova-module#24]
**Anyline Cordova Plugin version:** 
5.1.0

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[x] Android
[ ] iOS

**Current behavior:**
Failing on Android build.

**Expected behavior:**
Successful build.

**Steps to reproduce:**
1. ionic start myApp blank
2. ionic cordova platform add android
3. ionic cordova plugin add io-anyline-cordova
4. ionic cordova build android --verbose

**Related code:**
```
.
.
.
:app:transformNativeLibsWithMergeJniLibsForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libopencv_java3.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
41 actionable tasks: 1 executed, 40 up-to-date
Command finished with error code 1: ~/Projects/ionic/doc-scanner/platforms/android/gradlew cdvBuildDebug,-b,~/Projects/ionic/doc-scanner/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m
Error: ~/Projects/ionic/doc-scanner/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libopencv_java3.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
    at ChildProcess.whenDone (~/Projects/ionic/doc-scanner/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
~/Projects/ionic/doc-scanner/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libopencv_java3.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
[ERROR] An error occurred while running subprocess cordova.

        cordova build android --verbose exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 functions +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +15ms

```

**Other information:**
Ionic Angular version: 3.9.2
Ionic CLI version: 4.3.1
Cordova CLI version: 8.1.2
Cordova Android version: 7.1.2

**Comment by DonKanallie89** [comment]
Hey,

please try to add

`android.packagingOptions {
    pickFirst('lib/*/libgnustl_shared.so')
    pickFirst('lib/*/libopencv_java3.so')
}`

to your platforms/android/app/build.gradle. 
You can also set gradle properties in your Cordova directly, explained [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#configuring-gradle)

**Comment by JonasLaux** [comment]
Hey,

please try to add

android.packagingOptions { pickFirst('lib/*/libgnustl_shared.so') pickFirst('lib/*/libopencv_java3.so') }

to your platforms/android/app/build.gradle.
You can also set gradle properties in your Cordova directly, explained here

**Comment by YogliB** [comment]
Fixed it. Thank!
