### ISSUE TITLE
Plugin not working on Android with Ionic

### ISSUE THREAD

**Issue by YogliB** [Anyline/anyline-ocr-cordova-module#25]
**Anyline Cordova Plugin version:** 
5.2.0

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[x] Android
[ ] iOS

**Current behavior:**
When trying to start the plugin, there's a permission request, and then nothing happens (no error).

**Expected behavior:**
Plugin starting.

**Steps to reproduce:**
1. ionic start myApp blank
2. ionic cordova platform add android
3. ionic cordova plugin add io-anyline-cordova
4. ionic cordova run android // (with an emulator or a device connected)
5. start onAnylineClick() (via button for example)

**Related code:**
```
import { Component } from '@angular/core';
import { Platform, IonicPage } from 'ionic-angular';

declare const cordova: any;

@IonicPage({
  name: 'Home'
})
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  licenseKey ='<some key>';
  anylineConfig = {
    captureResolution: '720p',
    pictureResolution: '1080p',
    cutout: {
      style: 'rect',
      maxWidthPercent: '100%',
      maxHeightPercent: '100%',
      width: 720,
      ratioFromSize: {
        width: 10,
        height: 15
      },
      alignment: 'center',
      strokeWidth: 2,
      cornerRadius: 0,
      strokeColor: '00000000'
    },
    flash: {
      mode: 'manual',
      alignment: 'bottom_left',
      offset: {
        x: 10,
        y: 0
      }
    },
    beepOnResult: true,
    vibrateOnResult: true,
    blinkAnimationOnResult: true,
    cancelOnResult: false
  };

  constructor() {}

  onAnylineClick() {
    if (localStorage.getItem('hasStartedAnyline') === 'true') {
      return;
    }
    localStorage.setItem('hasStartedAnyline', 'true');

    cordova.exec(this._onResult, this._onError, 'AnylineSDK', 'scan', [
      this.licenseKey,
      this.anylineConfig
    ]);
  }

  private _onResult(result) {
    localStorage.setItem('hasStartedAnyline', 'false');
    console.log(result);
  }

  private _onError(error) {
    localStorage.setItem('hasStartedAnyline', 'false');
    //called if an error occurred or the user canceled the scanning
    if (error == 'Canceled') {
      //do stuff when user has canceled
      // this can be used as an indicator that the user finished the scanning if canclelOnResult is false
      console.log('AnylineOcr scanning canceled');
      return;
    }

    alert(error);
  }
}
```

**Other information:**
Ionic Angular version: 3.9.2
Ionic CLI version: 4.3.1
Cordova CLI version: 8.1.2
Cordova Android version: 7.1.2

**Comment by JonasLaux** [comment]
can you please provide the Log from Logcat?

**Comment by YogliB** [comment]
This is from after the app was opened, and right after I started the plugin ( I ran onAnylineClick() ).

```
11-14 13:37:32.169  2667 18918 E WakeLock: GCM_HB_ALARM release without a matched acquire!
11-14 13:37:36.607 23847 23913 D NET     : IOException:
11-14 13:37:37.732  2667  2684 I art     : Background partial concurrent mark sweep GC freed 125462(5MB) AllocSpace objects, 14(720KB) LOS objects, 40% free, 20MB/33MB, paused 3.657ms total 197.752ms
11-14 13:37:42.268   450   450 I cnss-daemon: RTM_NEWNEIGH message received: 28
11-14 13:37:42.269   450   450 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
11-14 13:37:46.830  5520 32357 V b3:tunnel:start:        event:emit   <--   BLOCKED, ssl.google-analytics.com, Thread[tunnel-178,5,main]
11-14 13:37:46.836  3710 12649 W GAv4-SVC: Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host "ssl.google-analytics.com": No address associated with hostname
11-14 13:37:46.846  2011  2011 E NotificationService: Suppressing notification from package by user request.
11-14 13:37:47.730   450   450 I cnss-daemon: RTM_NEWNEIGH message received: 28
11-14 13:37:47.732   450   450 E cnss-daemon: Stale or unreachable neighbors, ndm state: 16
11-14 13:37:50.087   450   450 I cnss-daemon: RTM_NEWROUTE Indication
11-14 13:37:50.089   450   450 E cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
11-14 13:37:50.089   450   450 E cnss-daemon: : 00:00:00:00:00:00
11-14 13:37:50.089   450   450 E cnss-daemon: Invalid mac address: 0x5560302110M
11-14 13:37:57.724   450   450 I cnss-daemon: RTM_NEWNEIGH message received: 28
11-14 13:37:57.726   450   450 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
11-14 13:38:09.482  2667  2667 I GeofencerStateMachine: sendNewTransitions called.
11-14 13:38:09.488  2667  4628 I GeofencerStateMachine: Location dropped because in deep still mode.
11-14 13:38:09.534  2667 11161 I GCoreUlr: Successfully inserted 1 locations
11-14 13:38:09.535  2667 11161 I UlrPolicyComputer: update - new computed state ID 427
11-14 13:38:11.512  3905  3983 W QCNEJ   : |CORE| CNE received unexpected action: android.intent.action.BATTERY_CHANGED
```

**Comment by JonasLaux** [comment]
Hey,
you are using an old config but with the new 'scan' Parameter. We are currently in the process of updating the documentation. But you have to use the old call with  
`
  cordova.exec(this._onResult, this._onError, 'AnylineSDK', 'YOU_SCAN_PLUGIN',...)
`
Or update your Configuration to >= Anyline 4.

**Comment by sharutza** [comment]
Hello

I'm getting an error with Ionic 4 
java.lang.RuntimeException: Unable to pause activity {be.rentacar.mobilerenttest/io.anyline.cordova.Anyline4Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.anyline.view.ScanViewPlugin.stop()' on a null object reference
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3961)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3927)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3901)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3872)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6650)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.anyline.view.ScanViewPlugin.stop()' on a null object reference
        at io.anyline.view.ScanView.stop(SourceFile:369)
        at io.anyline.cordova.Anyline4Activity.onPause(Anyline4Activity.java:102)
        at android.app.Activity.performPause(Activity.java:7242)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1409)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3950)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3927) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3901) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3872) 
        at android.app.ActivityThread.-wrap15(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6650) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818) 

When calling the cordova.exec(resolve, reject,  "AnylineSDK", "scan", this.opts); the loaded screen is black,and no other forms or camera.

this are the options:
 this.opts = [
        "--here comes my test licence key--",
        {
          "camera": {
            "captureResolution": "720"
          },
          "flash": {
            "mode": "manual",
            "alignment": "bottom_right"
          },
          "viewPlugin": {
            "plugin" : {
              "id" : "OCR_VC",
              "ocrPlugin" : {
                "scanMode" : "AUTO",
                "languages" : ["www/assets/anyline_capitals.traineddata"],
                "charWhitelist": "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                "validationRegex": "[A-Z0-9]{8}$",
                "minConfidence": 85
      
              }
            },
            "cutoutConfig": {
              "style": "rect",
              "maxWidthPercent": "80%",
              "maxHeightPercent": "80%",
              "alignment": "center",
              "width": 540,
              "ratioFromSize": {
                "width": 5,
                "height": 1
              },
              "strokeWidth": 2,
              "cornerRadius": 10,
              "strokeColor": "FFFFFF",
              "outerColor": "000000",
              "outerAlpha": 0.3,
              "feedbackStrokeColor": "0099FF"
            },
            "scanFeedback": {
              "style": "contour_point",
              "strokeWidth": 3,
              "strokeColor": "0099FF",
              "fillColor": "220099FF",
              "beepOnResult": true,
              "vibrateOnResult": true,
              "blinkAnimationOnResult": true
            },
            "cancelOnResult": true
          }
        }
      ]

**Comment by JonasLaux** [comment]
Hey, i shortly tried your config. Works on my side. 
Could you please create a new issue and fill out the issueing template providing all the needed informations?
We need to know which phone, which Android Version, when is it occuring, is it reproducable? Things like that. 
Thank you

**Comment by ahmadtaslimfuadi07** [comment]
how to use it in ionic 4?
