### ISSUE TITLE
IncompatibleClassChangeError 

### ISSUE THREAD

**Issue by joaoppedrosa** [Anyline/anyline-ocr-cordova-module#5]
I'm trying to run the `anyline.energy.js` example, but everytime that I run the method `anyline.energy.scanHeatMeterWithSegment()` in a Android device the app crash.

`Fatal Exception: java.lang.IncompatibleClassChangeError: com.google.android.gms.vision.barcode.internal.client.zzd$zza
       at com.google.android.gms.vision.barcode.internal.client.zzd.zzIg(Unknown Source)
       at com.google.android.gms.vision.barcode.internal.client.zzd.<init>(Unknown Source)
       at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
       at at.nineyards.anyline.camera.AnylineBaseView$a.<init>(SourceFile:846)
       at at.nineyards.anyline.camera.AnylineBaseView.enableBarcodeDetection(SourceFile:381)
       at io.anyline.cordova.EnergyActivity.initAnyline(EnergyActivity.java:197)
       at io.anyline.cordova.EnergyActivity.onCreate(EnergyActivity.java:147)
       at android.app.Activity.performCreate(Activity.java:6877)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by superqua** [comment]
Hi,

If you don't need the simultaneous barcode scanning in your app, you can set the `nativeBarcodeEnabled` flag in your config to `false` in the examples app.

Also, do you know wich buildToolsVersion you are using in your android project?

**Comment by joaoppedrosa** [comment]
I'm using BuildToolsVersion=25.0.2 and SdkVersion=android-24

**Comment by superqua** [comment]
We are trying to reproduce this error. In the meantime, can you try to to build the project with buildToolsVersion 24.0.3?

Also, did you try to turn off the nativeBarcodeEnabled?

**Comment by joaoppedrosa** [comment]
@superqua thanks, change the `nativeBarcodeEnabled` to `false` resolve the problem
