### ISSUE TITLE
Error building for iOS

### ISSUE THREAD

**Issue by EvanWieland** [Anyline/anyline-ocr-cordova-module#7]
First of all, I'm using Telerik Appbuilder to make my Cordova app. I have been able to get Android to build just fine with the Anyline Cordova plugin, but my build fails when building for iOS. Can you fellows find anything in this build log that looks like an obvious fix? I'm suspecting the `Warning: Path must be a string. Received false` error as the ultimate culprit but am not sure how to fix it. Thanks for your help!
```
Project "Anyline.tmp.proj" (default targets):
ios Build Tooling revision 2017.04.26.2r
Build Tooling Hostname mac.local
Warning: Failed to install 'io.anyline.cordova':TypeError: Path must be a string. Received false
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.projectConfig (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/cordova-lib/cordova-lib/src/cordova/util.js:212:25)
    at module.exports.context (/private/tmp/builds/Fe9aT3tjKte9ale9alL/app/Plugins/anyline/hooks/AfterPluginInstall.js:17:53)
    at runScriptViaModuleLoader (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/cordova-lib/cordova-lib/src/hooks/HooksRunner.js:192:18)
    at runScript (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/cordova-lib/cordova-lib/src/hooks/HooksRunner.js:170:16)
    at /Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/cordova-lib/cordova-lib/src/hooks/HooksRunner.js:155:20
    at _fulfilled (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/builder/BpcTooling/Cordova3/pm-6.4-/node_modules/q/q.js:749:13)
Warning: Path must be a string. Received false
Warning: /Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:156
throw Error("exit code: " + code);
^

Error: exit code: 1
    at Error (native)
    at ChildProcess.&lt;anonymous&gt; (/Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:156:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
Error: Build failed during execution
Error: 'Build failed with error code 1'
Error: 'Build failed with error code 1'
Done building project "Anyline.tmp.proj" -- FAILED.
```

**Comment by JonasLaux** [comment]
Hi,
this seems to be an issue of the right adding of the plugin with Telerik. I've not much experience with the appbuilder though, but i found in their Docu this hint:
http://docs.telerik.com/platform/appbuilder/troubleshooting/known-issues/known-issues-devices
to check the patch, because on iOS it's case sensetive. But at this one, it seems to not find any path. 
Can you also give us more information how exactly you added the plugin?

**Comment by EvanWieland** [comment]
Yeah. I'm not sure what the cli is doing behind the scenes, but this is what I run...
` appbuilder plugin add anyline`
Which yields...
```
The plugin 'anyline' was not found in our list of verified Cordova plugins. We will try to find it in npm and it will be fetched instead of added.

Cannot read property '$t' of undefined
```

It does fetch it from npm and installs, but does give that `property '$t' of undefined`. I haven't been able to find out where that error is from either.

**Comment by EvanWieland** [comment]
Turns out the `Cannot read property '$t' of undefined` error occurs on any plugin install via AppBuilder. I'm assuming the error is not related to the issue in question.

**Comment by EvanWieland** [comment]
So, in the plugin's `plugin.xml`, I removed the `<hook type="after_plugin_install" src="hooks/AfterPluginInstall.js" />` line of markup and everything seems to be building fine for iOS. I'm not sure what `AfterPluginInstall.js` was doing anyway, but everything seems to be working well now...
